# PLAY level variables
- name: variables from PLAY level
  hosts: localhost
  vars:
    Course: "DevOps"
    student: "dileep"
    Duration: "110HRS"
    triner: "subhash"
  tasks:
     - name: check variables
       ansible.builtin.debug:
         msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"
         msg: "Hi, I am learning {{Course}}, student name is {{Trainer}}, Duration is {{Duration}}"
      